name: Handle issues
on:
  issues:
    types: [opened]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "Issue Details ${{ toJSON(github.event.issues) }}"